baseURL: "https://roman.computer/"
title: "Roman Hauksson"
# paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Roman Hauksson
  description: "Roman Hauksson's blog."
  keywords: [Blog, Hugo, PaperMod]
  # author: Roman Hauksson
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2006 Jan 2"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    #favicon: "<link / abs url>"
    #favicon16x16: "<link / abs url>"
    #favicon32x32: "<link / abs url>"
    #apple_touch_icon: "<link / abs url>"
    #safari_pinned_tab: "<link / abs url>"

  label:
    text: "Roman Hauksson"
    # icon: /apple-touch-icon.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi, my name's Roman!"
    subtitle: |+
      I'm an undergraduate Computer Science student at the University of Texas at Dallas and the president of Effective Altruism UTD: a student group that aims to help students use the principles of [effective altruism](https://www.effectivealtruism.org/) to have a greater positive impact on the world using their career.

      I want to work full-time solving the world's most important and neglected problems and ensure humanity has a long and flourishing future. In particular, I'm pursuing technical research into [ensuring the safety of powerful AI systems](https://80000hours.org/problem-profiles/artificial-intelligence/).
    imageUrl: "Roman.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: "photo of Roman"
    buttons:
      # - name: learn more about me
      #   url: about
      - name: ✍️ read my posts
        url: posts

  # home-info mode
  homeInfoParams:
    Title: "Hi, my name's Roman!"
    Content: |+
      I'm an undergraduate Computer Science student at the University of Texas at Dallas and the co-founder and president of UTD's [effective altruism](https://www.effectivealtruism.org/) student group.

      I want to use my career to help solve the world's most important and neglected problems and ensure humanity has a long and flourishing future. In particular, I'm pursuing technical research to [prevent the development of powerful AI systems from threatening humanity's existence](https://80000hours.org/problem-profiles/artificial-intelligence/).

      ## more links

      - [Anonymous feedback form](https://forms.gle/DzMBXgbVa2WHjALVA): tell me what you think about me without fear of social reprisal  
      - [Course schedule](https://calendar.google.com/calendar/embed?src=2b7556e5a15bb37f1d425fe706f6fcda59d5bc118d6932c5d8369566b92d21df%40group.calendar.google.com): check to see if we're in the same class  
      - [Calendly](https://calendly.com/RomanHauksson/): book a virtual meeting with me  
      - [Focusmate](https://www.focusmate.com/user/romanhauksson): cowork with me  
      - [Discord](https://discordapp.com/users/888545144473780254) (`RomanHauksson#3458`): chat with me  
      - [Goodreads](https://www.goodreads.com/RomanHauksson): what I'm reading  
      - [Pocket](https://getpocket.com/@RomanHauksson): the articles and videos I like  
      - [UT Dallas website](https://personal.utdallas.edu/~roman): what I'm up to at UTD

  socialIcons:
    - name: github
      url: "https://github.com/romanhauksson"
    - name: linkedin
      url: "https://linkedin.com/in/romanhauksson"
    - name: cv
      url: "/resume.pdf"

  buttons:
    - name: example
      url: "https://example.com"
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"
  #   bing:
  #     SiteVerificationTag: "XYZabc"
  #   yandex:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/romanhn/roman.computer/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link
outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    # - identifier: search
    #   name: search
    #   url: /search/
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# for search
# https://adityatelange.github.io/hugo-PaperMod/posts/papermod/papermod-features/

permalinks:
  posts: /:filename/

markup:
  goldmark:
    renderer:
      unsafe: true